# Generated by Django 4.1.4 on 2022-12-10 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=14, unique=True, verbose_name="Nome"),
                ),
                ("load", models.IntegerField(verbose_name="Carga")),
                (
                    "repetitions",
                    models.IntegerField(verbose_name="Número de repetições"),
                ),
                ("series", models.IntegerField(verbose_name="Número de séries")),
            ],
        ),
    ]
