# Generated by Django 4.1.4 on 2022-12-11 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0002_alter_exercise_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscularGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exercise.exercise",
                        verbose_name="Exercício",
                    ),
                ),
            ],
        ),
    ]
