# Generated by Django 4.1.4 on 2022-12-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0003_musculargroup"),
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="exercise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exercise.exercise",
                verbose_name="Exercício",
            ),
        ),
    ]
