# Generated by Django 4.1.4 on 2022-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_alter_workout_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="end_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da finalização do treino"
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="goal",
            field=models.CharField(
                choices=[
                    ("loseWeight", "Emagrecimento"),
                    ("resistance", "Resistência"),
                    ("hypertrophy", "Hipertrofia"),
                    ("strength", "Força"),
                ],
                default="loseWeight",
                max_length=200,
                verbose_name="Objetivo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Treino ativo"),
        ),
    ]
