# Generated by Django 4.1.4 on 2022-12-29 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0003_workout_end_at_workout_goal_workout_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Criado em",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
